---
name: Robustness Nightly
permissions: read-all
on:
  pull_request:

  # workflow_dispatch enables manual testing of this job by maintainers
  workflow_dispatch:

jobs:
  main:
    # GHA has a maximum amount of 6h execution time, we try to get done within 3h
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: bs-wflw
      count: 150
      testTimeout: 200m
      artifactName: main
      runs-on: "['blacksmith-8vcpu-ubuntu-2204']"
      scenario: TestRobustnessExploratory
      lazyfsEnabled: true
